
name: Build Executable

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10.9'
          spec: 'lyricsgetter.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'lyricsGetter-win'
          options: --onefile, --name "lyricsGetter", --windowed
          
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10.9'
          spec: 'lyricsgetter.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'lyricsGetter-linux'
          options: --onefile --name "lyricsGetter", --windowed
